language: node_js
node_js:
  - "10"
  
script:
  - npm install
  - npm install surge -g
  - node_modules/.bin/gitbook install
  - node_modules/.bin/gitbook build
  - surge --domain http://multicourse-courseware.surge.sh/ --project ./_book